name: webdav_lastsync

on:
  schedule:
    - cron: '0 9,17 * * *'
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-18.04
    steps:
      - name: Fix
        run: |
          export SYNCFILE="lastsync.txt"
          export REMOTEFILE=" https://dav.jianguoyun.com/dav/zotero/${SYNCFILE}"
          touch ${SYNCFILE}
          curl -u ${JGY_EMAIL}:${JGY_DAVPASS} -T ${SYNCFILE} ${REMOTEFILE}
        env:
          JGY_EMAIL: ${{ secrets.JGY_EMAIL }}
          JGY_DAVPASS: ${{ secrets.JGY_DAVPASS }}